%% Clear memory and the command window
clear;
clc;

%% Load eeglab
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
ALLERP = buildERPstruct([]);
%% Set up variables holding key values 
    
% Dialog box to get info about script variables 
prompt    = {'Enter name of the grand average file:',...
             'Enter the list of bin numbers to plot:',...
             'Enter data collection location:'};
dlgtitle  =  'Input';
dims      =  [1 70];
definput  =  {'PROST_GA_2025_15Hz','68:70', 'hc'};
my_input  =  inputdlg(prompt,dlgtitle,dims,definput);

DIR       =  pwd;                       % Current folder (where the script should be located)
ga_name  =  my_input{1};   % import filename
bins      =  str2num(my_input{2});
location  =  my_input{3};
if strcmp(location, 'hc')
    channels = [27 21 22 19 15 8 12 4 5];
else
    channels = [3 2 29 8 23 24 14 13 19];
end

fname     = [ga_name '.erp'];

%% Load grand average waveform
ERP = pop_loaderp('filename', fname, 'filepath', DIR);
CURRENTERP = CURRENTERP + 1;
ALLERP(CURRENTERP) = ERP;    
erplab redraw;

%% Plot Grand Average Waveform

ERP = pop_ploterps( ERP, [bins], [ channels] ,...
                        'Axsize', [0.05 0.08],...
                        'BinNum', 'on', ...
                        'Blc', 'pre',...
                        'Box', [3 3],...
                        'ChLabel', 'on',...
                        'FontSizeChan', 14,...
                        'FontSizeLeg', 12, ...
                        'FontSizeTicks', 12, ...
                        'LegPos', 'right',...
                        'Linespec', {'b-.', 'r:', 'g-'},...
                        'LineWidth', 2,...
                        'Maximize', 'on',...
                        'Position', [68.6429 15.0714 106.857 31.9286], ...
                        'Style', 'Classic', ...
                        'Tag', 'ERP_figure',...
                        'Transparency', 0,...
                        'xscale', [-200.0 900.0   -200:200:800], ...
                        'yscale', [ -3.0 3.0   -3 :1:3], ...
                        'YDir', 'reverse');

erplab redraw;
