%% Clear memory and the command window
clear;
clc;

%% Load eeglab
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
ALLERP = buildERPstruct([]);
%% Set up variables holding key values 
    
% Dialog box to get info about script variables 
prompt    = {'Enter name of the grand average file:',...
             'Enter the list of bin numbers to plot separated by spaces:',...
             'Enter the number of intervals to plot separated by spaces:',...
             'Enter the start and end values (in ms) for each interval separated by spaces (e.g., 75 175 300 500):',...
             'Enter the minimum and maximum values for the scalp map separated by spaces (e.g., -5 5):'};
dlgtitle  =  'Input';
dims      =  [1 70];
definput  =  {'PROST_GA_2025_15Hz','81:84', '2' ,'300 500 500 800', '-2.25 2.25'};
my_input  =  inputdlg(prompt,dlgtitle,dims,definput)

DIR       =  pwd;          % Current folder (where the script should be located)
ga_name   =  my_input{1};   % import filename
bins      =  str2num(my_input{2});
intvl_num =  str2num(my_input{3});
intervals =  reshape(str2num(my_input{4}), intvl_num, 2)';
ylim      =  str2num(my_input{5});
fname     =  [ga_name '.erp'];

%% Load grand average waveform
ERP = pop_loaderp('filename', fname, 'filepath', DIR);
CURRENTERP = CURRENTERP + 1;
ALLERP(CURRENTERP) = ERP;    
erplab redraw;

%% Plot Grand Average Waveform

ERP = pop_scalplot( ERP,...
                    [ bins], ...
                    [ intervals], ...
                    'Blc', [ -100 0], ...
                    'Colorbar', 'on', ...
                    'Colormap', 'jet', ...
                    'Electrodes', 'on', ...
                    'FontName', 'Courier New', ...
                    'FontSize',  10, ...
                    'Legend', 'bn-bd-la', ...
                    'Maplimit', [ ylim], ...
                    'Mapstyle', 'both', ...
                    'Maptype', '2D', ...
                    'Mapview', '+X', ...
                    'Maximize', 'on',...
                    'Plotrad',  0.55, ...
                    'Value', 'mean' );

   erplab redraw;
