%% Clear memory and the command window
clear;
clc;

%% Load eeglab
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
ALLERP = buildERPstruct([]);
%% Set up variables holding key values 
    
% Dialog box to get info about script variables 
prompt    = {'Enter name of the grand average file:',...
             'Enter the list of bin numbers to plot:',...
             'Enter start and stop time for interval in ms:'};
dlgtitle  =  'Input';
dims      =  [1 70];
definput  =  {'prost_ga_202207_filtered_12Hz','85:88', '500 800'};
my_input  =  inputdlg(prompt,dlgtitle,dims,definput);

DIR       =  pwd;                       % Current folder (where the script should be located)
ga_name  =  my_input{1};   % import filename
bins      =  str2num(my_input{2});
interval  =  str2num(my_input{3});


fname     = [ga_name '.erp'];

%% Load grand average waveform
ERP = pop_loaderp('filename', fname, 'filepath', DIR);
CURRENTERP = CURRENTERP + 1;
ALLERP(CURRENTERP) = ERP;    
erplab redraw;

%% Plot Grand Average Waveform

ERP = pop_scalplot( ERP, [bins], [interval] ,...
                    'Blc', 'pre', ...
                    'Colorbar', 'on', ...
                    'Colormap', 'jet', ...
                    'Electrodes', 'on', ...
                    'FontName', 'Courier New',...
                    'FontSize',  10, ...
                    'Legend', 'bn-la', ...
                    'Maplimit', [ -3.0 3.0   ], ...
                    'Mapstyle', 'both', ...
                    'Maptype', '2D', ...
                    'Mapview', '+X', ...
                    'Maximize', 'on',...
                    'Plotrad',  0.55, ...
                    'Value', 'mean' );

erplab redraw;
