%% Clear memory and the command window
clear;
clc;

%% Load eeglab
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
ALLERP = buildERPstruct([]);
%% Set up variables holding key values 
    
% Dialog box to get info about script variables 
prompt    = {'Enter name of the grand average file:',...
             'Enter the list of bin numbers to plot:',...
             'Enter channel numbers to plot:'};
dlgtitle  =  'Input';
dims      =  [1 70];
definput  =  {'prost_ga_202207_filtered_12Hz','81:84', '18 13 14 6 9 11 12 4 5 7'};
my_input  =  inputdlg(prompt,dlgtitle,dims,definput);

DIR       =  pwd;                       % Current folder (where the script should be located)
ga_name  =  my_input{1};   % import filename
bins      =  str2num(my_input{2});
channels  =  str2num(my_input{3});


fname     = [ga_name '.erp'];

%% Load grand average waveform
ERP = pop_loaderp('filename', fname, 'filepath', DIR);
CURRENTERP = CURRENTERP + 1;
ALLERP(CURRENTERP) = ERP;    
erplab redraw;

%% Plot Grand Average Waveform

ERP = pop_ploterps( ERP, [bins], [ channels] ,...
                    'Axsize', [ 0.05 0.08], ...
                    'BinNum', 'on', ...
                    'Blc', 'pre', ...
                    'Box', [ 2 5], ...
                    'ChLabel','on', ...
                    'FontSizeChan',  14, ...
                    'FontSizeLeg',  12, ...
                    'FontSizeTicks',  12, ...
                    'LegPos', 'bottom', ...
                    'Linespec', {'r-' , 'r-.' , 'b-' , 'b-.' },...
                    'LineWidth',  2, ...
                    'Maximize', 'on', ...
                    'Position', [ 103.714 29.0556 106.857 31.8889], ...
                    'Style', 'Classic', ...
                    'Tag', 'ERP_figure', ...
                    'Transparency',  0,...
                    'xscale', [ -200.0 800.0   -200:200:800 ], ...
                    'YDir', 'reverse', ...
                    'yscale', [ -2.5 2.5   -3 -2.5 -1.5 -1:1 1.5 2.5 3 ] );

erplab redraw;
